baseURL = "https://studentz.github.io/masim/"
languageCode = "en-us"
title = "Mobile Agent"
theme = "m10c"

[params]
  author = "Pablo Ordonez"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/studentz"

